---
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Copy Apache config template
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache

- name: Enable mod_rewrite
  command: a2enmod rewrite
  notify: Restart Apache

- name: Ensure Apache service is running
  service:
    name: apache2
    state: started
    enabled: yes

