---
- name: Install PHP and required modules
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - libapache2-mod-php
    - php-mysql
  become: yes

- name: Copy PHP info file template
  template:
    src: phpinfo.php.j2
    dest: /var/www/html/phpinfo.php

- name: Ensure Apache service is reloaded
  service:
    name: apache2
    state: reloaded

