---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Copy MySQL config template
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart MySQL

- name: Secure MySQL Installation (enter root password)
  command: mysql_secure_installation
  args:
    creates: /root/.my.cnf

- name: Create MySQL Database
  mysql_db:
    name: mydatabase
    state: present
  become: yes

- name: Create MySQL User
  mysql_user:
    name: myuser
    password: "{{ mysql_root_password }}"
    host: localhost
    priv: 'mydatabase.*:ALL'
    state: present
  become: yes
